ALTER TABLE customer REPLICA IDENTITY USING INDEX customer_pkey;

ALTER TABLE lineitem REPLICA IDENTITY USING INDEX lineitem_pkey;

ALTER TABLE nation REPLICA IDENTITY USING INDEX nation_pkey;

ALTER TABLE orders REPLICA IDENTITY USING INDEX orders_pkey;

ALTER TABLE part REPLICA IDENTITY USING INDEX part_pkey;

ALTER TABLE partsupp REPLICA IDENTITY USING INDEX partsupp_pkey;

ALTER TABLE region REPLICA IDENTITY USING INDEX region_pkey;

ALTER TABLE supplier REPLICA IDENTITY USING INDEX supplier_pkey;
